# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cs_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depends_on', to='puzzle_hero.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Team')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Challenge')),
                ('required_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depends_on', to='puzzle_hero.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Team')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Flag')),
                ('submitter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Team')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Track')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Flag')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Track'),
        ),
    ]
