# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cs_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('initial_status', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('reward', models.IntegerField()),
                ('dependencies', models.ManyToManyField(related_name='_mission_dependencies_+', to='puzzle_hero.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='MissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Mission')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Team')),
            ],
        ),
        migrations.CreateModel(
            name='MissionStatusTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('initial_status', models.CharField(max_length=64)),
                ('sender', models.CharField(max_length=255)),
                ('en', models.CharField(max_length=255)),
                ('md_en', models.TextField()),
                ('fr', models.CharField(max_length=255)),
                ('md_fr', models.TextField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Mission')),
                ('required_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depends_on', to='puzzle_hero.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Post')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PostStatusTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Flag')),
                ('submitter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamScoreTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('initial_status', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_auth.Team')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='puzzle_hero.Track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatusTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Track')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[(1, 'trackstatus'), (2, 'missionstatus'), (3, 'poststatus'), (4, 'teamscore')], max_length=128)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Flag')),
            ],
        ),
        migrations.AddField(
            model_name='trackstatustrigger',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Trigger'),
        ),
        migrations.AddField(
            model_name='teamscoretrigger',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Trigger'),
        ),
        migrations.AddField(
            model_name='poststatustrigger',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Trigger'),
        ),
        migrations.AddField(
            model_name='missionstatustrigger',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Trigger'),
        ),
        migrations.AddField(
            model_name='mission',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Track'),
        ),
    ]
