# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionstatustrigger',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Trigger'),
        ),
        migrations.AlterField(
            model_name='poststatustrigger',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Trigger'),
        ),
        migrations.AlterField(
            model_name='teamscoretrigger',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Trigger'),
        ),
        migrations.AlterField(
            model_name='trackstatustrigger',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='puzzle_hero.Trigger'),
        ),
    ]
